# Generated by Django 5.1.4 on 2025-10-03 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreadinghistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userreadinghistory',
            name='article',
        ),
        migrations.RemoveField(
            model_name='userreadinghistory',
            name='user',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='UserReadingHistory',
        ),
    ]
