# Generated by Django 5.1.4 on 2025-10-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_userreadinghistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='anchoring_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
