# Generated by Django 5.1.4 on 2025-10-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_anchoring_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='anchoring_script',
        ),
        migrations.CreateModel(
            name='AnchoringScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='news.newsarticle')),
            ],
        ),
    ]
